name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Update setiap hari jam 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # IZIN untuk push/commit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Akbar330
          outputs: dist/github-contribution-grid-snake.gif

      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate contribution snake"
          add: "dist"
